#define TB_CRL MT(MOD_LCTL, KC_TAB)
#define TB_CMD MT(MOD_LGUI, KC_TAB)
#define RT_SHF MT(MOD_LSFT, KC_ENTER)
#define NV_SPC LT(3,KC_SPACE)
#define KC_ESC KC_ESCAPE
#define KC_EQ KC_EQUAL
#define _____ KC_TRANSPARENT
#define L_ALT KC_LEFT_ALT
#define L_SHFT KC_LEFT_SHIFT
#define L_GUI KC_LEFT_GUI
#define LCTL_LSFT_K LCTL(LSFT(KC_K))
#define KC_PGUP KC_PAGE_UP
#define KC_MUTE KC_AUDIO_MUTE
#define KC_VOLD KC_AUDIO_VOL_DOWN
#define KC_VOLU KC_AUDIO_VOL_UP
#define KC_PREVT KC_MEDIA_PREV_TRACK
#define KC_NEXTT KC_MEDIA_NEXT_TRACK
#define KC_PLAY KC_MEDIA_PLAY_PAUSE
#define SSHOT LGUI(LSFT(KC_S))
#define SLEEP KC_SYSTEM_SLEEP
#define KC_BDN KC_BRIGHTNESS_DOWN
#define KC_BUP KC_BRIGHTNESS_UP
#define QQOT LT(0, KC_QUOTE)
#define CMADSH LT(0, KC_COMMA)
#define PEREX LT(0, KC_DOT)
#define SLUND LT(0, KC_SLASH)
#define LABKSL LT(2, KC_LABK)
#define BOOT QK_BOOTLOADER
#define NV_BSE LT(1, KC_SPACE)
#define TAB_L LT(3, KC_PGUP)
#define TAB_R LT(3, KC_PGDN)
#define CUT LCTL(KC_X)
#define COPY LCTL(KC_C)
#define PASTE LCTL(KC_V)
#define VS_UP A(C(S(KC_3)))
#define VS_DN A(C(S(KC_GRAVE)))
#define VS_L A(C(S(KC_9)))
#define VS_R A(C(S(KC_0)))
#define MOJI LGUI(KC_DOT)
